[build.default]
foundry-project-root       = '.'
regen                      = true
rekompile                  = true
verbose                    = false
debug                      = false
require                    = 'test/_kontrol/solady-lemmas.k'
module-import              = 'X128MathLibTest:SOLADY-LEMMAS'
auxiliary-lemmas           = true
o2                         = true

[prove.default]
schedule                   = 'CANCUN'
foundry-project-root       = '.'
verbose                    = false
debug                      = false
max-depth                  = 100000
max-iterations             = 10000
reinit                     = false
cse                        = false
workers                    = 1
max-frontier-parallel      = 6
maintenance-rate           = 128
assume-defined             = true
no-log-rewrites            = true
no-stack-checks            = true
kore-rpc-command           = 'kore-rpc-booster --no-post-exec-simplify --equation-max-recursion 100 --equation-max-iterations 1000'
failure-information        = true
counterexample-information = true
minimize-proofs            = false
fail-fast                  = true
smt-timeout                = 16000
smt-retry-limit            = 0
break-every-step           = false
break-on-jumpi             = false
break-on-calls             = false
break-on-storage           = false
break-on-basic-blocks      = false
break-on-cheatcodes        = false
run-constructor            = false
symbolic-immutables        = false

[show.default]
foundry-project-root       = '.'
verbose                    = false
debug                      = false
use-hex-encoding           = false

[view-kcfg.default]
foundry-project-root       = '.'
use-hex-encoding           = true
